#!/usr/bin/env node
/**
 * Injects OPEN_WEATHER_GRAPH_API_KEY into src/pkjs/api-key-injected.js for dev/emulator.
 * That file is .gitignored. For release builds, do not run this (or delete the file)
 * so the app uses the key from the configuration page.
 */
const fs = require('fs');
const path = require('path');

const key = process.env.OPEN_WEATHER_GRAPH_API_KEY || '';
const outPath = path.join(__dirname, '..', 'src', 'pkjs', 'api-key-injected.js');
const content = "// Generated by scripts/inject-api-key.js – do not commit\nmodule.exports = { apiKey: " + JSON.stringify(key) + " };\n";

fs.writeFileSync(outPath, content, 'utf8');
console.log(key ? 'API key injected for dev build.' : 'API key cleared (release build).');
