#!/usr/bin/env node
/**
 * Reads the API key from api-key.txt (project root, gitignored) and writes
 * src/pkjs/api-key-injected.js so the app can use it without the Clay config.
 * If api-key.txt is missing or empty, writes an empty key (app falls back to Clay).
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const keyPath = path.join(root, 'api-key.txt');
let key = '';

if (fs.existsSync(keyPath)) {
  key = (fs.readFileSync(keyPath, 'utf8') || '').trim();
}
if (!key && process.env.OPEN_WEATHER_GRAPH_API_KEY) {
  key = process.env.OPEN_WEATHER_GRAPH_API_KEY.trim();
}

const outPath = path.join(root, 'src', 'pkjs', 'api-key-injected.js');
const content = "// Generated by scripts/inject-api-key.js – do not commit\nmodule.exports = { apiKey: " + JSON.stringify(key) + " };\n";

fs.writeFileSync(outPath, content, 'utf8');
console.log(key ? 'API key loaded from api-key.txt for dev build.' : 'No API key in api-key.txt; app will use Clay config.');
