#!/usr/bin/env node
/**
 * Reads the API key from api-key.txt (project root, gitignored) and writes
 * src/pkjs/api-key-injected.js so the app can use it without the Clay config.
 * If api-key.txt is missing or empty, writes an empty key (app falls back to Clay).
 * Optional: inject fixed coordinates to bypass geolocation (avoids hang when geo never resolves).
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const keyPath = path.join(root, 'api-key.txt');
let key = '';

if (fs.existsSync(keyPath)) {
  key = (fs.readFileSync(keyPath, 'utf8') || '').trim();
}
if (!key && process.env.OPEN_WEATHER_GRAPH_API_KEY) {
  key = process.env.OPEN_WEATHER_GRAPH_API_KEY.trim();
}

// Fixed coordinates so app doesn't hang on geolocation. Set false to use real geo again.
const useDevCoords = true;
const DEV_COORDS = { lat: 39.58, lon: -105.02 };
let lat = process.env.OPEN_WEATHER_GRAPH_LAT != null ? parseFloat(process.env.OPEN_WEATHER_GRAPH_LAT) : (useDevCoords ? DEV_COORDS.lat : null);
let lon = process.env.OPEN_WEATHER_GRAPH_LON != null ? parseFloat(process.env.OPEN_WEATHER_GRAPH_LON) : (useDevCoords ? DEV_COORDS.lon : null);
const useCoords = lat != null && lon != null && !Number.isNaN(lat) && !Number.isNaN(lon);

const outPath = path.join(root, 'src', 'pkjs', 'api-key-injected.js');
let content = "// Generated by scripts/inject-api-key.js – do not commit\nmodule.exports = { apiKey: " + JSON.stringify(key);
if (useCoords) {
  content += ", lat: " + lat + ", lon: " + lon;
}
content += " };\n";

fs.writeFileSync(outPath, content, 'utf8');
console.log(key ? 'API key loaded from api-key.txt for dev build.' : 'No API key in api-key.txt; app will use Clay config.');
if (useCoords) {
  console.log("Injected coordinates: " + lat + ", " + lon + " (geolocation bypassed).");
}
